# Generated by Django 3.0.6 on 2020-06-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_write', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
