# Generated by Django 3.0.6 on 2020-06-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('read_write', '0002_auto_20200616_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('grade', models.IntegerField(default=0)),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
    ]
