# Generated by Django 3.0.6 on 2020-06-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_write', '0003_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='story',
            name='graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='comments',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='story',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
