# Generated by Django 3.0.6 on 2020-06-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_write', '0004_auto_20200616_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='story',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
