# Generated by Django 3.0.6 on 2020-06-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_write', '0005_auto_20200619_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
