# Generated by Django 3.0.6 on 2020-06-22 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_write', '0006_story_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.CharField(default='---', max_length=100),
        ),
        migrations.AlterField(
            model_name='story',
            name='comments',
            field=models.TextField(default='---'),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(default='---'),
        ),
        migrations.AlterField(
            model_name='story',
            name='email',
            field=models.CharField(default='---', max_length=50),
        ),
        migrations.AlterField(
            model_name='story',
            name='text',
            field=models.TextField(default='---'),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(default='---', max_length=100),
        ),
    ]
