# Generated by Django 3.1.4 on 2022-03-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_write', '0008_story_feedback_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='comments2',
            field=models.TextField(default='---'),
        ),
        migrations.AddField(
            model_name='story',
            name='grade2',
            field=models.IntegerField(default=0),
        ),
    ]
